### ISSUE TITLE
New Map G.O.S Leskovets

### ISSUE THREAD

**Issue by scooby78** [scooby78/160thSOR#46]
http://steamcommunity.com/sharedfiles/filedetails/?id=855464203

**Comment by Deek356** [comment]
I can comment

**Comment by yettie79** [comment]
Whats going on with this map?

**Comment by Deek356** [comment]
Ive tested it with groups of 15 people max. Air, inf and mech. We've run it
twice on Friday, no issues.
Either needs to have the testing checklist applied to certify it for sunday
or we just run it on a Sunday and see.
There are no reported issues with it in steam community pages.
Its a cup based map.

On 8 Nov 2017 2:54 PM, "yettie79" <notifications@github.com> wrote:

Whats going on with this map?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/scooby78/160thSOR/issues/46#issuecomment-342703608>,
or mute
the thread

**Comment by yettie79** [comment]
We need to put this to the community as i have been informed that a large number of members do not want this map.

**Comment by AmTheAgent** [comment]
We did that over a month ago, the results were for, not against. I will send you the Survey Form so you can see results and re-post if necessary. This community NEEDS good new maps that perform well.

**Comment by scooby78** [comment]
Ok let’s mark this for the next community meeting..

**Comment by AmTheAgent** [comment]
Guessing you guys weren't told about Monday's Community meeting? There was a lot of conversation about these issues in particular, maps. Not so much mods.

**Comment by Deek356** [comment]
"you have been informed that a large number of members dont want this map"
is that you have been informed by one person or a couple of people that a
large number of members dont want this map?
or have a significant number (over 15)  members have come to you and said
that they dont want this map?

Can we get clarity on that comment please.

Considering that this map has been tested on a Friday twice with up to 15
people on each occasion with the feedback from those who tested it was
recorded on the Steam page. All but 1 person were pro the map.

I think we need to have clarity on what the process is for inclusion of a
map into the mod pack. The process needs to be upfront and clear.
What we need to avoid is the smallest minority having the largest voice.

consideration needs to be given to "what percentage of members need to be
PRO a map for it to be included".
Additionally, how is this vote conducted, is it a community meeting that
can be easily be stacked with members who are either pro or anti a map if
they know its coming to a vote?
The way in which provide members the opportunity to vote needs to be open
and transparent as well as available over a period in time rather than a
stamp in time.

I brought this map to the community in early September and followed the map
testing process. The intent was to proactively get newer maps into the mod
pack, which at the time no one else was doing so that we could get some
variety in map types. The map is based on Cup and file size is relatively
small, 143 meg. This would make the testing and inclusion into the
community much easier process. Think of it as a test.
I like that map a lot but getting it specifically added to the mod pack was
not the underlying premise, having variety in maps is. I support the
process of having new maps and giving the community the pathway's to get
them included.

**Comment by scooby78** [comment]
Based on the above, I see no reason not to continue as discussed last Sunday, nothing should change for a “Sunday missions only” status.  We can discuss it at a community meeting ‘post’ pack insertion to solve further underlying debates..

Given its size and with the list of possible maps, I’m sure we are always going to add maps that not everyone will like.

**Comment by yettie79** [comment]
Deek as per my post "a number of members" is more then 1. 
also i think the main issue is, it was tested and passed, however it was never asked if the community wanted it. 
I not sure is pushing it in anyway will set a good standard, especially when mods/maps are a contentious issue at this time.
We can do a vote tonight after mission, this will feed the dogs!!

**Comment by AmTheAgent** [comment]
TO be accurate. There was a Community Vote Yettie.

**Comment by yettie79** [comment]
I have talked to both lith and meat, who run the community meeting. they said their has never been a vote.

maybe it was talked about within maps in general?

so what i see is a communication break down.

**Comment by AmTheAgent** [comment]
Sorry to say, they are incorrect. I know Meat Voted though he may have forgotten. 

https://docs.google.com/forms/d/1bLjAtaEaBiIJEKTHReq_WykYf1QULhDy2e1b8ANQEI8/edit?usp=drivesdk

We only got 23 responses - 87% FOR , 13% Against the Form is still there if you want to use it.


[ModMap Inclusion Survey (Responses).pdf](https://github.com/scooby78/160thSOR/files/1473303/ModMap.Inclusion.Survey.Responses.pdf)

**Comment by Litheius** [comment]
*Enter Litheius*

Lads,

Agreed that there needs to be a defined format for introducing new maps, one that passes all the technical requirements and ensures the wider community is on board with it.
I know we already have some sort of system but I think most people aren't aware of it.... I'm a bit hazy on it myself.

More importantly...one thing that people agreed upon on Monday was that new maps really need to be given a proper test on a Sunday as the small scale tests don't paint an accurate picture in regards to a lot of things. 

As Yettie said above, Meat, Yettie and myself talked about whether or not an actual straw poll vote took place in a community meeting and neither of us were aware of that happening, neither were others we've talked to. That survey is from a Sunday? Dated 1.10.17 which was a Sunday, hence why we didn't believe there was a community meeting vote. Either way I still think 23 is a decent enough turn out for any sort of vote. 

I know we normally say 30 votes are needed for something to pass but i'm not fussed either way. If we need 30+ people we can, and as Yettie said, easily vote after tonights mission as to whether people are fine to test it on a Sunday and then re-vote directly after the first mission takes place on that map on a Sunday Op as to whether they want it to stay.

This map aside, the main thing from me is making sure we've got a smooth system for map implementation that ticks the technical side and community side, and allows for a reasonably smooth pathway to Sunday tests, where the real testing happens.

Love Lith.

**Comment by yettie79** [comment]
Thank you. 
I stand corrected, I will pass this onto the members with issues.
Excellent job keeping the info!

on the other side the vote should be done on a community meeting and DEEK could we please get that added to the mod testing guide. 

I am happy that a legitimate process has been followed and support pushing into mod pack.

good work all.

**Comment by patkill** [comment]
yeah well your mum's a Leskovets so there, am i doing this right? my first post here guys.

**Comment by Deek356** [comment]
Acknowledged all.

**Comment by Diesel486** [comment]
for all involved here is a basic questionnaire for mod testing purposes, can also apply to maps I guess. if you feel it needs tweaks please let me know

https://docs.google.com/forms/d/1F3_nEThKkuXFmgHY8sk2WUAGOQaQNrC-_QJiptv1vSI/prefill

**Comment by AmTheAgent** [comment]
Good contribution Patty, well done :D haha 

No Link Diesss...

**Comment by Diesel486** [comment]
seems i broke it somehow, am fixing it now

**Comment by Diesel486** [comment]
https://goo.gl/forms/tptv7Q8h2AAh4s923
try that one

**Comment by Deek356** [comment]
The board has asked me to work on the Mod and Map testing check list/guide.
I would welcome group support as I believe we would be able to get good
knowledge and points of view which we could work into document and progress
it quickly.  Let me know those who are interested.

**Comment by Diesel486** [comment]
feel free to come bug me later, got some good ideas that have served me well so far

**Comment by scooby78** [comment]
Approved for sunday missions
